# Generated by Django 5.1.6 on 2025-07-14 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_message_receiver_alter_message_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
