# Generated by Django 5.1.6 on 2025-07-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0007_chat_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='created_at',
        ),
    ]
