# Generated by Django 5.1.6 on 2025-07-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0011_remove_wishlist_created_alter_wishlist_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner_picture',
            field=models.ImageField(blank=True, null=True, upload_to='owner_picture'),
        ),
    ]
