# Generated by Django 5.1.6 on 2025-07-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0013_alter_product_owner_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
